### ISSUE TITLE
Expose the 10 latest repositories as RSS/Atom feed

### ISSUE THREAD

**Issue by bzg** [AntoineAugusti/api-codes-sources-fr#1]
The `.json` file with the 10 latest repositories is useful for some editorialisation on the frontend.

It would be nice to have a separate `.xml` RSS 2.0 or Atom 1.0 feed that people could subscribe to.

**Comment by AntoineAugusti** [comment]
This is an API. I don't want people to subscribe to a RSS feed on an API subdomain. Clients can build a RSS or Atom feed using content from the API

**Comment by bzg** [comment]
I was considering this repository to be some sort of temporary backend for https://github.com/bzg/codegouvfr - but I see your point, I will set up a minimal backend exposing the RSS feed.

**Comment by AntoineAugusti** [comment]
Don't implement this just yet. I think this is a secondary feature. I might do it here, but it seems not to be the appropriate place.

**Comment by AntoineAugusti** [comment]
Maybe with this lib https://github.com/lkiesow/python-feedgen

**Comment by bzg** [comment]
I plan to use https://github.com/yogthos/clj-rss in a minimal backend, it is very straightforward.

We can discuss IRL: I'd rather you focus on the API (there a lot to do here) and me focusing on the backend/client.
