### ISSUE TITLE
Get the avatar URL of organizations

### ISSUE THREAD

**Issue by bzg** [AntoineAugusti/api-codes-sources-fr#5]
I'd to use cards to display organizations. It would be great to get the `avatar_url` value, as available from the [API](https://developer.github.com/v3/orgs/#get-an-organization). 

![2019-07-25-200620_1920x1080_scrot](https://user-images.githubusercontent.com/63500/61897669-d9852100-af17-11e9-941c-27551f536bff.png)

Thanks!

**Comment by AntoineAugusti** [comment]
Hello @bzg,

Issues asking for new data should be directed to the other repo. This one only exposes data as an API but is not meant to collect additional data.

**Comment by AntoineAugusti** [comment]
Implemented in https://github.com/etalab/data-codes-sources-fr/commit/d485371768ae94efa0d7049f3c2fdd3c217c755b

**Comment by bzg** [comment]
:man_facepalming: Sorry again, and thanks for implementing this!
