### ISSUE TITLE
Get the number of followers for an organization

### ISSUE THREAD

**Issue by bzg** [AntoineAugusti/api-codes-sources-fr#6]
We do have the number of `stars` for repositories, it seems consistent to get the number of `followers` for an organization.

**Comment by AntoineAugusti** [comment]
Hello @bzg,

Issues asking for new data should be directed to the other repo. This one only exposes data as an API but is not meant to collect additional data. 

Regarding this feature, I think that followers for orgs is not used on GitHub and not a thing for Gitlab. Can you make sure it's a thing?

**Comment by bzg** [comment]
I see `followers` in GitHub's [API documentation](https://developer.github.com/v3/orgs/#get-an-organization).  You can get the list of `members` of a GitLab project, but the [API documentation](https://docs.gitlab.com/ee/api/#project-resources) but the notion is different, so I'll leave this FR aside for now.

**Comment by AntoineAugusti** [comment]
@bzg it exists in the API but it doesn't seem to be used. Example: https://api.github.com/orgs/etalab
